version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - json-server
    restart: always

  json-server:
    image: clue/json-server
    volumes:
      # 경로를 frontend/server/db.json으로 지정
      - ./frontend/server/db.json:/data/db.json
    ports:
      - "3000:3000"
    restart: always